name = "knuclebones-worker"
main = "dist/index.mjs"
compatibility_date = "2022-09-08"
usage_model = "bundled"
workers_dev = false

durable_objects.bindings = [
  { name = "GAME_STATE_STORE", class_name = "GameStateStore" },
  { name = "WEB_SOCKET_STORE", class_name = "WebSocketStore" }
]

[build]
command = "yarn build"

[[migrations]]
tag = "v1"
new_classes = ["GameStateStore"]

[[migrations]]
tag = "v2"
new_classes = ["WebSocketStore"]

[env.staging]
name = "knucklebones-worker-staging"
route = { pattern = "staging.api.knucklebones.io", custom_domain = true, zone_name = "knucklebones.io" }
durable_objects.bindings = [
  { name = "GAME_STATE_STORE", class_name = "GameStateStore" },
  { name = "WEB_SOCKET_STORE", class_name = "WebSocketStore" }
]

[env.production]
name = "knucklebones-worker-production"
route = { pattern = "api.knucklebones.io", custom_domain = true, zone_name = "knucklebones.io" }
durable_objects.bindings = [
  { name = "GAME_STATE_STORE", class_name = "GameStateStore" },
  { name = "WEB_SOCKET_STORE", class_name = "WebSocketStore" }
]
