name = "knuclebones-worker"
main = "dist/index.mjs"
compatibility_date = "2022-09-08"
workers_dev = false

durable_objects.bindings = [
  { name = "GAME_STATE_DURABLE_OBJECT", class_name = "GameStateDurableObject" },
  { name = "WEB_SOCKET_DURABLE_OBJECT", class_name = "WebSocketDurableObject" }
]

[build]
command = "yarn build"

[[migrations]]
tag = "v1"
new_classes = ["GameStateStore"]

[[migrations]]
tag = "v2"
new_classes = ["WebSocketStore"]

[[migrations]]
tag = "v3"
renamed_classes = [{from = "GameStateStore", to = "GameStateDurableObject"}, {from = "WebSocketStore", to = "WebSocketDurableObject"}]

[env.staging]
name = "knucklebones-worker-staging"
route = { pattern = "staging.api.knucklebones.io", custom_domain = true, zone_name = "knucklebones.io" }
durable_objects.bindings = [
  { name = "GAME_STATE_DURABLE_OBJECT", class_name = "GameStateDurableObject" },
  { name = "WEB_SOCKET_DURABLE_OBJECT", class_name = "WebSocketDurableObject" }
]

[env.production]
name = "knucklebones-worker-production"
route = { pattern = "api.knucklebones.io", custom_domain = true, zone_name = "knucklebones.io" }
durable_objects.bindings = [
  { name = "GAME_STATE_DURABLE_OBJECT", class_name = "GameStateDurableObject" },
  { name = "WEB_SOCKET_DURABLE_OBJECT", class_name = "WebSocketDurableObject" }
]
