name = "knuclebones-worker"
main = "dist/index.mjs"
compatibility_date = "2022-09-08"
node_compat = true

[build]
command = "yarn build"

[durable_objects]
bindings = [{name = "GAME_STATE_DURABLE", class_name = "GameStateDurable"}]

[[migrations]]
tag = "v1"
new_classes = ["GameStateDurable"]
