env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
    - tsconfig.node.json
    - functions/tsconfig.json
plugins:
  - react
  - react-hooks
  - prettier
rules:
  prettier/prettier: error
  # max-len:
  #   - error
  #   - code: 80
  space-before-function-paren: off
  "@typescript-eslint/space-before-function-paren":
    - error
    - asyncArrow: always
      named: never
      anonymous: always
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/method-signature-style":
    - error
    - method
  "@typescript-eslint/no-non-null-assertion": off
