env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - apps/front/tsconfig.json
    - apps/worker/tsconfig.json
    - packages/common/tsconfig.json
plugins:
  - react
  - react-hooks
  - prettier
rules:
  prettier/prettier: error
  space-before-function-paren: off
  '@typescript-eslint/space-before-function-paren':
    - error
    - asyncArrow: always
      named: never
      anonymous: always
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/method-signature-style':
    - error
    - method
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/restrict-template-expressions': off
  'react/no-unescaped-entities': off
