name: Deploy Worker Staging

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          # Possibilité d'utiliser un cache si nécessaire
          run_install: true
      
      - name: Deploy Staging
        uses: cloudflare/wrangler-action@v3
        with:
          # Variables dépréciées, il faut utiliser `CLOUDFLARE_`
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/worker'
          packageManager: pnpm
          environment: staging
