name: Deploy Worker Production

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - uses: actions/checkout@v2


      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          # Possibilité d'utiliser un cache si nécessaire
          run_install: true

      - name: Build Worker
        run: pnpm build
      
      - name: Deploy Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'apps/worker'
          command: deploy --env=production
